CREATE TABLE IF NOT EXISTS `${prefix}credentials`
(
    `CREDENTIAL_NUMBER` INTEGER  NOT NULL,
    `SECRET`            LONGTEXT NOT NULL,
    PRIMARY KEY (`CREDENTIAL_NUMBER`)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;
