CREATE TABLE IF NOT EXISTS `${prefix}credentials`
(
    `CREDENTIAL_NUMBER` INTEGER  NOT NULL,
    'REFRESH_TOKEN'     LONGTEXT NOT NULL,
    `ACCESS_TOKEN`      LONGTEXT NOT NULL,
    PRIMARY KEY (`CREDENTIAL_NUMBER`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
