# noinspection SqlResolveForFile

ALTER TABLE `${prefix}announcements`
    MODIFY ENABLED BIT(1) NOT NULL DEFAULT 1,
    MODIFY INFO_ONLY BIT(1) NOT NULL DEFAULT 0;

ALTER TABLE `${prefix}api`
    MODIFY BLOCKED BIT(1) NOT NULL DEFAULT 0;

ALTER TABLE `${prefix}calendars`
    MODIFY EXTERNAL BIT(1) NOT NULL DEFAULT 0;

ALTER TABLE `${prefix}guild_settings`
    MODIFY EXTERNAL_CALENDAR BIT(1) NOT NULL DEFAULT 0,
    MODIFY SIMPLE_ANNOUNCEMENT BIT(1) NOT NULL DEFAULT 0,
    MODIFY PATRON_GUILD BIT(1) NOT NULL DEFAULT 0,
    MODIFY DEV_GUILD BIT(1) NOT NULL DEFAULT 0,
    MODIFY 12_HOUR BIT(1) NOT NULL DEFAULT 1,
    MODIFY BRANDED BIT(1) NOT NULL DEFAULT 0;