export enum TaskType {
    RSVP_GET, RSVP_UPDATE,

	GUILD_SETTINGS_GET, GUILD_SETTINGS_UPDATE,

	WEB_GUILD_GET, WEB_GUILD_UPDATE,

	CALENDAR_GET, CALENDAR_LIST, CALENDAR_UPDATE, CALENDAR_DELETE,

	ANNOUNCEMENT_GET, ANNOUNCEMENT_LIST, ANNOUNCEMENT_CREATE,
	ANNOUNCEMENT_UPDATE, ANNOUNCEMENT_DELETE,

	EVENT_LIST_DATE, EVENT_LIST_MONTH, EVENT_LIST_RANGE,
	EVENT_CREATE, EVENT_DELETE, EVENT_GET, EVENT_UPDATE
}