version: "3"

services:
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # This is only for local debugging and development. DO NOT USE IN PRODUCTION!!!!!
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=discal
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=discal
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  api:
    image: rg.nl-ams.scw.cloud/dreamexposure/discal-server:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./.docker/api:/discal
    working_dir: /discal
    depends_on:
      - mysql
      - redis

  cam:
    image: rg.nl-ams.scw.cloud/dreamexposure/discal-cam:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8081:8080"
      - "5006:5005"
      - "8008:8008"
    volumes:
      - ./.docker/cam:/discal
    working_dir: /discal
    depends_on:
      - mysql
      - redis
      - api

  bot:
    image: rg.nl-ams.scw.cloud/dreamexposure/discal-client:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5007:5005"
    volumes:
      - ./.docker/bot:/discal
    working_dir: /discal
    depends_on:
      - mysql
      - redis
      - api
      - cam

  web:
    image: rg.nl-ams.scw.cloud/dreamexposure/discal-web:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "3000:8080"
      - "5008:5005"
    volumes:
      - ./.docker/web:/discal
    working_dir: /discal
    depends_on:
      - api

volumes:
  discal_data: {}
