name: Gradle Build And Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.0

      # Install NPM
      - name: Install NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14.8.0

      # Install JDK 16
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Build project and have jib push images to private container registry
      - name: Build with Gradle
        env:
          SCW_USER: ${{ secrets.SCW_USER }}
          SCW_SECRET: ${{ secrets.SCW_SECRET }}
          BUILD_NUMBER: $GITHUB_RUN_NUMBER
        run: gradlew clean build jib -Djib.to.auth.username=${SCW_USER} -Djib.to.auth.password=${SCW_SECRET}
